package br.com.pitanga.view;

import br.com.pitanga.dao.model.RelatorioDAO;
import br.com.pitanga.dao.model.VendaDAO;
import br.com.pitanga.domain.Venda;
import br.com.pitanga.table.cellrenderer.VendaCellRenderer;
import br.com.pitanga.table.model.VendaTableModel;
import br.com.pitanga.util.GUIUtils;
import br.com.pitanga.dao.DAOFactory;
import br.com.pitanga.domain.Empresa;
import br.com.pitanga.domain.Usuario;
import br.com.pitanga.mail.MailSender;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author douglas
 * @date 12/09/2015
 * @time 09:54:16
 */
public class FrmConsultaVenda extends javax.swing.JDialog {

    private List<Venda> vendas = new ArrayList<>();

    private Empresa empresa;
    private Usuario usuario;

    /**
     * Creates new form FrmImprimirVenda
     *
     * @param parent
     * @param modal
     * @param empresa
     * @param usuario
     */
    public FrmConsultaVenda(JFrame parent, boolean modal, Empresa empresa, Usuario usuario) {
        super(parent, modal);
        initComponents();
        initialize();
        this.empresa = empresa;
        this.usuario = usuario;
        lbEmail.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupBuscarPor = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVenda = new javax.swing.JTable();
        btSair = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tfPesquisa = new javax.swing.JTextField();
        rbCodigoVenda = new javax.swing.JRadioButton();
        rbNomeCliente = new javax.swing.JRadioButton();
        rbDataVenda = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cbOrdem = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tbVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbVenda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbVenda);

        btSair.setMnemonic('S');
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pitanga/img/print_16x16.png"))); // NOI18N
        jButton1.setMnemonic('p');
        jButton1.setText("imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por"));

        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyReleased(evt);
            }
        });

        btnGroupBuscarPor.add(rbCodigoVenda);
        rbCodigoVenda.setText("Código da venda");
        rbCodigoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCodigoVendaActionPerformed(evt);
            }
        });

        btnGroupBuscarPor.add(rbNomeCliente);
        rbNomeCliente.setText("Nome do cliente");
        rbNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomeClienteActionPerformed(evt);
            }
        });

        btnGroupBuscarPor.add(rbDataVenda);
        rbDataVenda.setText("Data da venda");
        rbDataVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDataVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPesquisa)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbNomeCliente)
                        .addGap(18, 18, 18)
                        .addComponent(rbCodigoVenda)
                        .addGap(18, 18, 18)
                        .addComponent(rbDataVenda)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCodigoVenda)
                    .addComponent(rbNomeCliente)
                    .addComponent(rbDataVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Ordenar por:");

        cbOrdem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código da venda", "Nome do cliente", "Mais recente", "Mais antigo", "Maior valor", "Menor valor" }));
        cbOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrdemActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pitanga/img/update_16x16.png"))); // NOI18N
        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pitanga/img/delete_16x16.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pitanga/img/mail_16x16.png"))); // NOI18N
        jButton3.setText("Enviar por e-mail");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Período"));

        jLabel2.setText("Inicio:");

        jLabel3.setText("Fim:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbEmail.setText("enviando...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbOrdem, 0, 304, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSair))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(btExcluir)
                    .addComponent(jButton3)
                    .addComponent(lbEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        imprimirVenda();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbCodigoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCodigoVendaActionPerformed
        tfPesquisa.setText("");
        tfPesquisa.requestFocus();
        preencherTabela();
    }//GEN-LAST:event_rbCodigoVendaActionPerformed

    private void tfPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyReleased
        String termo = tfPesquisa.getText();
        if (rbNomeCliente.isSelected()) {
            buscarNomeCliente(termo);
        } else if (rbCodigoVenda.isSelected()) {
            buscarCodigoCliente(termo);
        } else if (rbDataVenda.isSelected()) {
            buscarDataVenda(termo);
        }
    }//GEN-LAST:event_tfPesquisaKeyReleased

    private void rbNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomeClienteActionPerformed
        tfPesquisa.setText("");
        tfPesquisa.requestFocus();
        preencherTabela();
    }//GEN-LAST:event_rbNomeClienteActionPerformed

    private void cbOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrdemActionPerformed
        tfPesquisa.setText("");
        preencherTabela();
    }//GEN-LAST:event_cbOrdemActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluirVenda();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void rbDataVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDataVendaActionPerformed
        tfPesquisa.setText("");
        tfPesquisa.requestFocus();
        preencherTabela();
    }//GEN-LAST:event_rbDataVendaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        alterarVenda();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        lbEmail.setText("Enviando e-mail...");
        enviarVenda();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void initialize() {
        this.rbNomeCliente.setSelected(true);
        this.cbOrdem.setSelectedIndex(0);
        this.setTitle("Pitanga System - Vendas");
        GUIUtils.considerarEnterComoTab(this);
        preencherTabela();
    }

    private void preencherTabela() {
        int ordem = cbOrdem.getSelectedIndex();
        VendaDAO vd = DAOFactory.getDefaultDAOFactory().getVendaDAO();
        this.vendas = vd.listarTodos(ordem);
        if (this.vendas != null) {
            this.tbVenda.setModel(new VendaTableModel(this.vendas));
            this.tbVenda.setDefaultRenderer(Object.class, new VendaCellRenderer());
        }
    }

    private void imprimirVenda() {
        int selecionada = -1;
        selecionada = this.tbVenda.getSelectedRow();
        if (selecionada == -1) {
            JOptionPane.showMessageDialog(rootPane,
                    "- NENHUMA VENDA SELECIONADA -",
                    "Pitanga System - IMPRIMIR",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            RelatorioDAO obj = DAOFactory.getDefaultDAOFactory().getRelatorioDAO();
            VendaTableModel vtm = new VendaTableModel(vendas);
            Venda venda = vtm.get(selecionada);
            JasperViewer jv = obj.imprimirVenda(venda);
            FrmReport frmReport = new FrmReport(this, venda.getDescricaoTela(), true, jv);
            frmReport.setVisible(true);
        }
    }

    private void enviarVenda() {
        int selecionada = tbVenda.getSelectedRow();
        if (selecionada == -1) {
            JOptionPane.showMessageDialog(rootPane,
                    "- NENHUMA VENDA SELECIONADA -",
                    "Pitanga System - ENVIAR",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            VendaTableModel vtm = new VendaTableModel(vendas);
            Venda venda = vtm.get(selecionada);
            MailSender mailSender = new MailSender();
            mailSender.enviarVenda(venda);
        }
        
         lbEmail.setText("");
    }

    private void buscarNomeCliente(String nome) {
        List<Venda> lista = new ArrayList<>();
        for (Venda v : this.vendas) {
            if ((v.getCliente().getNome().toUpperCase()).contains(nome.toUpperCase())) {
                lista.add(v);
            }
        }
        tbVenda.setModel(new VendaTableModel(lista));
        tbVenda.setDefaultRenderer(Object.class, new VendaCellRenderer());
    }

    private void buscarCodigoCliente(String codigo) {
        List<Venda> lista = new ArrayList<>();
        for (Venda v : this.vendas) {
            if (("" + v.getIdVenda()).contains(codigo)) {
                lista.add(v);
            }
        }
        tbVenda.setModel(new VendaTableModel(lista));
        tbVenda.setDefaultRenderer(Object.class, new VendaCellRenderer());
    }

    private void buscarDataVenda(String termo) {
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        List<Venda> lista = new ArrayList<>();
        for (Venda v : this.vendas) {
            String data = formatador.format(v.getDataVenda());
            if (data.contains(termo)) {
                lista.add(v);
            }
        }
        tbVenda.setModel(new VendaTableModel(lista));
        tbVenda.setDefaultRenderer(Object.class, new VendaCellRenderer());
    }

    private void excluirVenda() {
        int selecionada = tbVenda.getSelectedRow();
        if (selecionada == -1) {
            JOptionPane.showMessageDialog(rootPane,
                    "- NENHUMA VENDA SELECIONADA -",
                    "Pitanga System - EXCLUIR",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {

            VendaDAO vd = DAOFactory.getDefaultDAOFactory().getVendaDAO();
            Venda venda = new Venda();
            venda = vd.buscar(Integer.parseInt(
                    (this.tbVenda.getValueAt(selecionada, 0)).toString()));
            FrmConfirmaExclusaoVenda confirmaExclusaoVenda = new FrmConfirmaExclusaoVenda(this, true, venda);
            confirmaExclusaoVenda.setVisible(true);

//            Long codigo = venda.getIdVenda();
//            String nome = venda.getCliente().getNome();
//            int i = JOptionPane.showConfirmDialog(null,
//                    "DESEJA MESMO EXCLIUR A VENDA ABAIXO?\n\n"
//                    + "- Código: " + String.format("%05d", codigo)
//                    + "\n- Cliente: " + nome + "\n\n"
//                    + "ATENÇÃO: Essa ação removerá todos os TÍTULOS e ITENS associados a essa venda.",
//                    "Pitanga System - Confirmação de exclusão",
//                    JOptionPane.YES_NO_OPTION);
//            if (i == JOptionPane.YES_OPTION) {
//                vd.remover(codigo);
//                preencherTabela();
//            }
            preencherTabela();
        }
    }

    private void alterarVenda() {
        int selecionada = tbVenda.getSelectedRow();
        if (selecionada == -1) {
            JOptionPane.showMessageDialog(rootPane,
                    "- NENHUMA VENDA SELECIONADA -",
                    "Pitanga System - ALTERAR",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            FrmVenda frmVenda = new FrmVenda(this, empresa, usuario, vendas, selecionada);
            frmVenda.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSair;
    private javax.swing.ButtonGroup btnGroupBuscarPor;
    private javax.swing.JComboBox cbOrdem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JRadioButton rbCodigoVenda;
    private javax.swing.JRadioButton rbDataVenda;
    private javax.swing.JRadioButton rbNomeCliente;
    private javax.swing.JTable tbVenda;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
}
