
package br.com.pitanga.view;

import br.com.pitanga.dao.model.FornecedorDAO;
import br.com.pitanga.dao.model.ProdutoDAO;
import br.com.pitanga.domain.Fornecedor;
import br.com.pitanga.domain.ItemCompra;
import br.com.pitanga.domain.Produto;
import br.com.pitanga.domain.TituloCompra;
import br.com.pitanga.dao.DAOFactory;
import br.com.pitanga.dao.model.CompraDAO;
import br.com.pitanga.dao.model.ItemCompraDAO;
import br.com.pitanga.dao.model.TituloCompraDAO;
import br.com.pitanga.domain.Compra;
import br.com.pitanga.table.model.ItemCompraTableModel;
import br.com.pitanga.util.StringUtils;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Netsul
 */
public class FrmCompra extends javax.swing.JDialog {

    /**
     * Creates new form FrmCompra
     * @param parent
     * @param modal
     */
    public FrmCompra(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNovo = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCpfCnpj = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfRgInscricao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        tfCelular = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfCep = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        tfCodigoCidade = new javax.swing.JTextField();
        tfNomeCidade = new javax.swing.JTextField();
        tfUfCidade = new javax.swing.JTextField();
        btFolderFornecedor = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tfCodigoFornecedor = new javax.swing.JTextField();
        btGravar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItemCompra = new javax.swing.JTable();
        btSearchProduto = new javax.swing.JButton();
        tfDescricao = new javax.swing.JTextField();
        tfCodigoProduto = new javax.swing.JTextField();
        tfValorCompra = new javax.swing.JTextField();
        tfQuantidade = new javax.swing.JTextField();
        tfValorItem = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfDesconto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btAddItem = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        tfSubDesconto = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfSubTotal = new javax.swing.JTextField();
        btParcelamento = new javax.swing.JButton();
        lbParcelamento = new javax.swing.JLabel();
        tfQuantParcela = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfDataCompra = new javax.swing.JFormattedTextField();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btNovo.setMnemonic('N');
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btCancelar.setMnemonic('C');
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Cliente"));

        jLabel1.setText("Nome:");

        tfNome.setEditable(false);
        tfNome.setBackground(new java.awt.Color(255, 255, 255));
        tfNome.setFocusable(false);

        tfEndereco.setEditable(false);
        tfEndereco.setBackground(new java.awt.Color(255, 255, 255));
        tfEndereco.setFocusable(false);

        jLabel2.setText("Endereço:");

        jLabel3.setText("CPF/CNPJ:");

        tfCpfCnpj.setEditable(false);
        tfCpfCnpj.setBackground(new java.awt.Color(255, 255, 255));
        tfCpfCnpj.setFocusable(false);

        jLabel4.setText("RG/Insc.:");

        tfRgInscricao.setEditable(false);
        tfRgInscricao.setBackground(new java.awt.Color(255, 255, 255));
        tfRgInscricao.setFocusable(false);

        jLabel6.setText("Número:");

        tfNumero.setEditable(false);
        tfNumero.setBackground(new java.awt.Color(255, 255, 255));
        tfNumero.setFocusable(false);

        jLabel7.setText("Bairro:");

        tfBairro.setEditable(false);
        tfBairro.setBackground(new java.awt.Color(255, 255, 255));
        tfBairro.setFocusable(false);

        jLabel8.setText("Telefone:");

        jLabel9.setText("Celular:");

        jLabel10.setText("E-mail:");

        tfTelefone.setEditable(false);
        tfTelefone.setBackground(new java.awt.Color(255, 255, 255));
        tfTelefone.setFocusable(false);

        tfCelular.setEditable(false);
        tfCelular.setBackground(new java.awt.Color(255, 255, 255));
        tfCelular.setFocusable(false);

        tfEmail.setEditable(false);
        tfEmail.setBackground(new java.awt.Color(255, 255, 255));
        tfEmail.setFocusable(false);

        jLabel11.setText("CEP:");

        tfCep.setEditable(false);
        tfCep.setBackground(new java.awt.Color(255, 255, 255));
        tfCep.setFocusable(false);

        jLabel12.setText("UF:");

        jLabel13.setText("Cidade:");

        lbCodigo.setText("Cod. fornecedor:");

        tfCodigoCidade.setEditable(false);
        tfCodigoCidade.setBackground(new java.awt.Color(255, 255, 255));
        tfCodigoCidade.setFocusable(false);

        tfNomeCidade.setEditable(false);
        tfNomeCidade.setBackground(new java.awt.Color(255, 255, 255));
        tfNomeCidade.setFocusable(false);

        tfUfCidade.setEditable(false);
        tfUfCidade.setBackground(new java.awt.Color(255, 255, 255));
        tfUfCidade.setFocusable(false);

        btFolderFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pitanga/img/pesquisa_16x16.png"))); // NOI18N
        btFolderFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFolderFornecedorActionPerformed(evt);
            }
        });

        jLabel14.setText("Cod. cidade:");

        tfCodigoFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCodigoFornecedorFocusLost(evt);
            }
        });
        tfCodigoFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCodigoFornecedorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(tfBairro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(tfTelefone))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCodigoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(tfNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfUfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(tfEmail)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfCodigoFornecedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btFolderFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tfRgInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfRgInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btFolderFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfCodigoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfUfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btGravar.setMnemonic('G');
        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder()));

        tbItemCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbItemCompra.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbItemCompra);

        btSearchProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pitanga/img/pesquisa_16x16.png"))); // NOI18N
        btSearchProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchProdutoActionPerformed(evt);
            }
        });

        tfCodigoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCodigoProdutoFocusLost(evt);
            }
        });
        tfCodigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCodigoProdutoKeyTyped(evt);
            }
        });

        tfValorCompra.setText("0,00");
        tfValorCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfValorCompraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfValorCompraFocusLost(evt);
            }
        });

        tfQuantidade.setText("0,00");
        tfQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfQuantidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfQuantidadeFocusLost(evt);
            }
        });

        tfValorItem.setText("0,00");

        jLabel15.setText("Cód. produto:");

        jLabel16.setText("Descrição:");

        jLabel17.setText("Quant.:");

        jLabel18.setText("Valor Unit.:");

        jLabel19.setText("Valor Total:");

        tfDesconto.setText("0,00");
        tfDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDescontoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDescontoFocusLost(evt);
            }
        });

        jLabel5.setText("Desc. (%) :");

        btAddItem.setMnemonic('A');
        btAddItem.setText("Add");
        btAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddItemActionPerformed(evt);
            }
        });

        jLabel21.setText("Desconto (R$) :");

        tfSubDesconto.setEditable(false);
        tfSubDesconto.setBackground(new java.awt.Color(153, 255, 153));
        tfSubDesconto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tfSubDesconto.setText("0,00");

        jLabel22.setText("Sub-total:");

        tfSubTotal.setEditable(false);
        tfSubTotal.setBackground(new java.awt.Color(153, 255, 153));
        tfSubTotal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tfSubTotal.setText("0,00");

        btParcelamento.setMnemonic('P');
        btParcelamento.setText("Parcelamento");
        btParcelamento.setToolTipText("P");
        btParcelamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParcelamentoActionPerformed(evt);
            }
        });

        lbParcelamento.setForeground(java.awt.Color.blue);
        lbParcelamento.setText("Nenhuma parcela lançada.");

        tfQuantParcela.setEditable(false);
        tfQuantParcela.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfCodigoProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSearchProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfValorCompra)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDesconto)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btParcelamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbParcelamento, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfQuantParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSubDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btSearchProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btAddItem)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel5)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tfValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(tfSubDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(tfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btParcelamento)
                        .addComponent(lbParcelamento)
                        .addComponent(tfQuantParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setText("Data Compra:");

        try {
            tfDataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btSair.setMnemonic('S');
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tfDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btNovo)
                    .addComponent(btCancelar)
                    .addComponent(btGravar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        novaCompra();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        inicializarFrame();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btFolderFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFolderFornecedorActionPerformed
        FrmBuscaFornecedor obj = new FrmBuscaFornecedor(this);
        obj.setVisible(true);
    }//GEN-LAST:event_btFolderFornecedorActionPerformed

    private void tfCodigoFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodigoFornecedorFocusLost
        if (!((this.tfCodigoFornecedor.getText().trim()).equals(""))) {
            Fornecedor fornecedor = new Fornecedor();

            FornecedorDAO cd = DAOFactory.getDefaultDAOFactory().getFornecedorDAO();
            fornecedor = cd.buscar(Integer.parseInt(this.tfCodigoFornecedor.getText()));

            preencherCamposFornecedor(fornecedor);
        }
    }//GEN-LAST:event_tfCodigoFornecedorFocusLost

    private void tfCodigoFornecedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoFornecedorKeyTyped
        StringUtils obj = new StringUtils();
        obj.somenteNumeros(evt, this);
    }//GEN-LAST:event_tfCodigoFornecedorKeyTyped

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        if (this.tfCodigoFornecedor.getText().isEmpty() || this.tfCodigoFornecedor.getText().equals("00000")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, informe o fornecedor.");
            this.tfCodigoFornecedor.requestFocus();
        } else if (this.itens.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Lance pelo menos um item.");
        } else if (titulos.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Informe pelo menos uma parcela.");
            btParcelamento.requestFocus();
        } else if (verificaValorCompra()) {
            try {
                gravarCompra();
                try {
                    gravarItem();
                    
                } catch (SQLException ex) {
                    Logger.getLogger(FrmCompra.class.getName()).log(Level.SEVERE, null, ex);
                }
                gravarTitulo();
                alterarQtdProduto();
                atualizarCompra();
            } catch (ParseException ex) {
                Logger.getLogger(FrmCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btGravarActionPerformed

    private void btSearchProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchProdutoActionPerformed
        // TODO add your handling code here:
        FrmBuscaProduto obj = new FrmBuscaProduto(this, this);
        obj.setVisible(true);
    }//GEN-LAST:event_btSearchProdutoActionPerformed

    private void tfCodigoProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodigoProdutoFocusLost

        if (!((this.tfCodigoProduto.getText().trim()).equals(""))) {

            Produto produto = new Produto();

            ProdutoDAO pd = DAOFactory.getDefaultDAOFactory().getProdutoDAO();
            produto = pd.buscar(Integer.parseInt(this.tfCodigoProduto.getText()));

            preencherCamposProduto(produto);
        }
    }//GEN-LAST:event_tfCodigoProdutoFocusLost

    private void tfCodigoProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoProdutoKeyTyped
        StringUtils obj = new StringUtils();
        obj.somenteNumeros(evt, this);
    }//GEN-LAST:event_tfCodigoProdutoKeyTyped

    private void tfValorCompraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfValorCompraFocusGained
        this.tfValorCompra.selectAll();
    }//GEN-LAST:event_tfValorCompraFocusGained

    private void tfValorCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfValorCompraFocusLost

        if (!(this.tfCodigoProduto.getText().trim()).equals("")) {
            double valor = Double.parseDouble(this.tfValorCompra.getText().replace(",", "."));
            if (valor == 0) {
                JOptionPane.showMessageDialog(rootPane, "O valor unitário não deve ser zero (0,00).");
            }
        }
        calculaValorItem();

        double desconto = Double.parseDouble(this.tfValorCompra.getText().replace(",", "."));
        StringUtils.formatarDecimal(desconto);
        //obj.formatarDecimal(tfValorCompra, desconto);
    }//GEN-LAST:event_tfValorCompraFocusLost

    private void tfQuantidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfQuantidadeFocusGained
        this.tfQuantidade.selectAll();
    }//GEN-LAST:event_tfQuantidadeFocusGained

    private void tfQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfQuantidadeFocusLost
        calculaValorItem();

        double quantidade = Double.parseDouble(this.tfQuantidade.getText().replace(",", "."));
        StringUtils.formatarDecimal(quantidade);
    }//GEN-LAST:event_tfQuantidadeFocusLost

    private void tfDescontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDescontoFocusGained
        this.tfDesconto.selectAll();
    }//GEN-LAST:event_tfDescontoFocusGained

    private void tfDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDescontoFocusLost

       

        double desconto = Double.parseDouble(this.tfDesconto.getText().replace(",", "."));
        if (desconto > 100) {
            JOptionPane.showMessageDialog(rootPane, "O valor do desconto não pode\n"
                    + "ser maior que 100%. (" + StringUtils.formatarDecimal(desconto) + "%)");
            this.tfDesconto.requestFocus();
        } else if (desconto < 0) {
            JOptionPane.showMessageDialog(rootPane, "O valor do desconto não pode\n"
                    + "ser menor que 0%. (" + StringUtils.formatarDecimal(desconto) + "%)");
            this.tfDesconto.requestFocus();
        } else {
            StringUtils.formatarDecimal(desconto);
            calculaValorItem();
        }
    }//GEN-LAST:event_tfDescontoFocusLost

    private void btAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddItemActionPerformed

        if (evt.getID() == 10) {
            JOptionPane.showMessageDialog(rootPane, "apertou enter");
        }

        if (!(this.tfCodigoProduto.getText().trim().equals(""))) {

            double desconto = Double.parseDouble(this.tfDesconto.getText().replace(",", "."));
            double valor = Double.parseDouble(this.tfValorCompra.getText().replace(",", "."));
            double quantidade = Double.parseDouble(this.tfQuantidade.getText().replace(",", "."));
            Produto produto = new Produto();
            produto.setIdProduto(Integer.parseInt(this.tfCodigoProduto.getText()));
            produto.setDescricao(this.tfDescricao.getText());
            adicionarItem(desconto, valor, quantidade, produto);

        } else {
            JOptionPane.showMessageDialog(rootPane, "Nenhum produto selecionado");
        }
    }//GEN-LAST:event_btAddItemActionPerformed

    private void btParcelamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParcelamentoActionPerformed
        if (this.tfDataCompra.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(rootPane, "Informe a data da venda!");
        } else if (this.tfSubTotal.getText().equals("0,00")) {
            JOptionPane.showMessageDialog(rootPane, "Não é possível parcelar uma venda\n"
                    + "com valor total iqual a 0,00 (zero)");
        } else {
            try {
                double valorVenda = Double.parseDouble(this.tfSubTotal.getText().replace(",", "."));
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

                Date dataVenda = sdf.parse(this.tfDataCompra.getText());

                FrmTituloCompra obj = new FrmTituloCompra(this, true, titulos, valorVenda, dataVenda, lbParcelamento, tfQuantParcela);
                obj.setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(FrmVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btParcelamentoActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private boolean verificaValorCompra() {

        double somaParcelas = 0.00;
        double valorCompra = Double.parseDouble(tfValorCompra.getText().replace(",", "."));

        if (!titulos.isEmpty()) {
            for (TituloCompra tv : titulos) {
                somaParcelas += tv.getValorParcela();
            }
        }

        return somaParcelas != valorCompra;
    }

    private void preencherTabela() {
        this.itens = preencherItens();
        if (this.itens != null) {
            this.tbItemCompra.setModel(new ItemCompraTableModel(this.itens));
            //this.tbItemVenda.setDefaultRenderer(Object.class, new ItemVendaCellRenderer());
        }
    }

    private List<ItemCompra> preencherItens() {
        List<ItemCompra> lista = new ArrayList<>();
        ItemCompraDAO cd = DAOFactory.getDefaultDAOFactory().getItemCompraDAO();
        lista = cd.listarTodos();

        return lista;
    }

    private void inicializarFrame() {
        preencherTabela();
        // Habilita/desabilita os botões
        this.btNovo.setEnabled(true);
        this.btSair.setEnabled(true);
        this.btCancelar.setEnabled(false);
        this.btFolderFornecedor.setEnabled(false);
        this.btGravar.setEnabled(false);
        this.btSearchProduto.setEnabled(false);
        this.btAddItem.setEnabled(false);
        this.btParcelamento.setEnabled(false);
        // Desabilita a tabela
        this.tbItemCompra.setEnabled(false);
        // Desabilita os campos  
        this.tfDataCompra.setEnabled(false);
        this.tfCodigoFornecedor.setEnabled(false);
        this.tfNome.setEnabled(false);
        this.tfCpfCnpj.setEnabled(false);
        this.tfRgInscricao.setEnabled(false);
        this.tfEndereco.setEnabled(false);
        this.tfNumero.setEnabled(false);
        this.tfBairro.setEnabled(false);
        this.tfCep.setEnabled(false);
        this.tfCodigoCidade.setEnabled(false);
        this.tfNomeCidade.setEnabled(false);
        this.tfUfCidade.setEnabled(false);
        this.tfTelefone.setEnabled(false);
        this.tfCelular.setEnabled(false);
        this.tfEmail.setEnabled(false);
        this.tfCodigoProduto.setEnabled(false);
        this.tfDescricao.setEnabled(false);
        this.tfQuantidade.setEnabled(false);
        this.tfValorCompra.setEnabled(false);
        this.tfDesconto.setEnabled(false);
        this.tfValorItem.setEnabled(false);
        this.tfSubDesconto.setEnabled(false);
        this.tfSubTotal.setEnabled(false);
        this.tfQuantParcela.setVisible(false);
        // Limpa os campos
        this.tfDataCompra.setText(null);
        this.tfCodigoFornecedor.setText("");
        this.tfNome.setText("");
        this.tfEndereco.setText("");
        this.tfNumero.setText("");
        this.tfBairro.setText("");
        this.tfCep.setText("");
        this.tfCodigoCidade.setText("");
        this.tfNomeCidade.setText("");
        this.tfUfCidade.setText("");
        this.tfCpfCnpj.setText("");
        this.tfRgInscricao.setText("");
        this.tfTelefone.setText("");
        this.tfCelular.setText("");
        this.tfEmail.setText("");
        this.tfSubDesconto.setText("0,00");
        this.tfSubTotal.setText("0,00");
        this.titulos.removeAll(titulos);
        this.lbParcelamento.setText("Nenhuma parcela lançada.");
        this.lbParcelamento.setEnabled(false);
        // Seta o título para o frame
        this.setTitle("Pitanga System - Venda");
        // Instancia a classe Complemento
        this.itens.removeAll(itens);

    }

    void preencherCamposFornecedor(Fornecedor fornecedor) {
        this.tfCodigoFornecedor.setText(String.format("%05d", fornecedor.getIdFornecedor()));
        this.tfNome.setText(fornecedor.getNomeFornecedor());
        this.tfCpfCnpj.setText(fornecedor.getCpfCnpjFornecedor());
        this.tfRgInscricao.setText(fornecedor.getRgFornecedor());
        this.tfEndereco.setText(fornecedor.getEnderecoFornecedor());
        this.tfNumero.setText(fornecedor.getNumeroFornecedor());
        this.tfBairro.setText(fornecedor.getBairroFornecedor());
        this.tfCep.setText(fornecedor.getCepFornecedor());
        this.tfCodigoCidade.setText("" + fornecedor.getCidade().getIdCidade());
        //this.tfNomeCidade.setText(fornecedor.getCidade().getNomeCidade());
        //this.tfUfCidade.setText(fornecedor.getCidade().getUf());
        this.tfTelefone.setText(fornecedor.getTelefoneFornecedor());
        this.tfCelular.setText(fornecedor.getCelularFornecedor());
        this.tfEmail.setText(fornecedor.getEmailFornecedor());
    }

    private void gravarItem() throws SQLException {

        if (!this.itens.isEmpty()) {
            CompraDAO compraDao = DAOFactory.getDefaultDAOFactory().getCompraDAO();
            Compra compra = compraDao.getUltimaCompra();
            for (ItemCompra iv : itens) {
                ItemCompra item = new ItemCompra();
                Produto produto = new Produto();
                item.setDesconto(iv.getDesconto());
                produto.setIdProduto(iv.getProduto().getIdProduto());
                item.setProduto(produto);
                item.setQuantidade(iv.getQuantidade());
                item.setValor(iv.getValor());
                item.setCompra(compra);
                ItemCompraDAO itemDao = DAOFactory.getDefaultDAOFactory().getItemCompraDAO();
                itemDao.inserir(item);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nenhum item foi lançado.");
        }

    }

    private void gravarTitulo() throws ParseException {

        if (!this.itens.isEmpty()) {
            CompraDAO compraDAO = DAOFactory.getDefaultDAOFactory().getCompraDAO();
            Compra compra = compraDAO.getUltimaCompra();
            for (TituloCompra tv : titulos) {
                TituloCompra titulo = new TituloCompra();
                titulo.setCompra(compra);
                titulo.setNumParcela(tv.getNumParcela());
                titulo.setValorParcela(tv.getValorParcela());
                titulo.setVencimento(tv.getVencimento());
                TituloCompraDAO tituloDAO = DAOFactory.getDefaultDAOFactory().getTituloCompraDAO();
                tituloDAO.inserir(titulo);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Nenhum Título informado.");
        }
    }

    void preencherCamposProduto(Produto produto) {
        this.tfCodigoProduto.setText(String.format("%05d", produto.getIdProduto()));
        this.tfDescricao.setText(produto.getDescricao());
        this.tfValorCompra.setText(new DecimalFormat("#,##0.00").format(produto.getValorVenda()));
    }

    private void calculaValorItem() {
        double quantidade = Double.parseDouble(this.tfQuantidade.getText().replace(",", "."));
        double valorUnitario = Double.parseDouble(this.tfValorCompra.getText().replace(",", "."));
        double desconto = Double.parseDouble(this.tfDesconto.getText().replace(",", "."));

        double valorItem = (quantidade * valorUnitario) - ((quantidade * valorUnitario) * (desconto / 100));

        this.tfValorItem.setText(new DecimalFormat("###0.00").format(valorItem));
    }

    private void adicionarItem(double desconto, double valor, double quantidade, Produto produto) {
        ItemCompra item = new ItemCompra();
        item.setProduto(produto);
        item.setQuantidade(quantidade);
        item.setValor(valor);
        item.setDesconto(desconto);
        this.itens.add(item);
        this.tbItemCompra.setModel(new ItemCompraTableModel(itens));

        double subDesconto = 0.00;
        double subTotal = 0.00;
        for (ItemCompra iv : itens) {
            subDesconto += ((iv.getQuantidade() * iv.getValor()) * (iv.getDesconto() / 100));
            subTotal += ((iv.getValor() * iv.getQuantidade()) - ((iv.getValor() * iv.getQuantidade()) * (iv.getDesconto() / 100)));
        }

        StringUtils strUtil = new StringUtils();

        this.tfSubDesconto.setText(strUtil.formatarDecimalTabela(subDesconto));
        this.tfSubTotal.setText(strUtil.formatarDecimalTabela(subTotal));
        this.tfCodigoProduto.setText(null);
        this.tfDescricao.setText(null);
        this.tfQuantidade.setText("0,00");
        this.tfValorCompra.setText("0,00");
        this.tfDesconto.setText("0,00");
        this.tfValorItem.setText("0,00");
        this.tfCodigoProduto.requestFocus();
    }

    private void novaCompra() {
        // Botões
        this.btNovo.setEnabled(false);
        this.btSair.setEnabled(false);
        this.btCancelar.setEnabled(true);
        this.btFolderFornecedor.setEnabled(true);
        this.btGravar.setEnabled(true);
        this.btSearchProduto.setEnabled(true);
        this.btAddItem.setEnabled(true);
        this.btParcelamento.setEnabled(true);
        // Tabela 
        this.tbItemCompra.setEnabled(true);
        // Campos
        this.tfCodigoFornecedor.setEnabled(true);
        this.tfNome.setEnabled(true);
        this.tfCpfCnpj.setEnabled(true);
        this.tfRgInscricao.setEnabled(true);
        this.tfEndereco.setEnabled(true);
        this.tfNumero.setEnabled(true);
        this.tfBairro.setEnabled(true);
        this.tfCep.setEnabled(true);
        this.tfTelefone.setEnabled(true);
        this.tfCelular.setEnabled(true);
        this.tfEmail.setEnabled(true);
        this.tfCodigoCidade.setEnabled(true);
        this.tfNomeCidade.setEnabled(true);
        this.tfUfCidade.setEnabled(true);
        this.tfCodigoProduto.setEnabled(true);
        this.tfDescricao.setEnabled(true);
        this.tfQuantidade.setEnabled(true);
        this.tfValorCompra.setEnabled(true);
        this.tfDesconto.setEnabled(true);
        this.tfValorItem.setEnabled(true);
        this.tfSubDesconto.setEnabled(true);
        this.tfSubTotal.setEnabled(true);
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        this.tfDataCompra.setText(formatador.format(data));
        this.tfDataCompra.setEnabled(true);
        // Setar foco
        this.tfCodigoFornecedor.requestFocus();
        this.lbParcelamento.setEnabled(true);
    }

    private void gravarCompra() throws ParseException {
        Compra compra = new Compra();
        Fornecedor fornecedor = new Fornecedor();

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date dataCompra = sdf.parse(this.tfDataCompra.getText());

        compra.setDataCompra(dataCompra);
        fornecedor.setIdFornecedor(Integer.parseInt(this.tfCodigoFornecedor.getText()));
        compra.setFornecedor(fornecedor);

        CompraDAO compraDao = DAOFactory.getDefaultDAOFactory().getCompraDAO();
        compraDao.inserir(compra);
    }

    private void alterarQtdProduto() {
        List<ItemCompra> lista = new ArrayList<>();
        //int id = 0;
        //int qtd = 0;
        lista.stream().forEach((listas) -> {
            int id = listas.getProduto().getIdProduto();
            int qtd = (int) listas.getQuantidade();
            ProdutoDAO produtoDAO = DAOFactory.getDefaultDAOFactory().getProdutoDAO();
            produtoDAO.alterarQuantidade(qtd, id);
            System.out.println("Id" + id);
            System.out.println("Qtd" + qtd);
        });

    }

    private void atualizarCompra() {
        CompraDAO compraDao = DAOFactory.getDefaultDAOFactory().getCompraDAO();

        Compra ultimaVenda = compraDao.getUltimaCompra();

        Compra compra = new Compra();

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date dataVenda = null;
        try {
            dataVenda = sdf.parse(this.tfDataCompra.getText());
        } catch (ParseException ex) {
            Logger.getLogger(FrmCompra.class.getName()).log(Level.SEVERE, null, ex);
        }

        compra.setIdCompra(ultimaVenda.getIdCompra());
        compra.setDataCompra(dataVenda);
        compra.setFornecedor(ultimaVenda.getFornecedor());
        compra.setValorCompra(Double.parseDouble(this.tfSubTotal.getText().replace(",", ".")));
        compra.setValorDesconto(Double.parseDouble(this.tfSubDesconto.getText().replace(",", ".")));
        compra.setQuantParcela(Integer.parseInt(this.tfQuantParcela.getText()));

        System.out.println(
                "\n\n-------------------------------------------------\n"
                + "IdVenda: " + ultimaVenda.getIdCompra() + "\n"
                + "dataVenda: " + dataVenda + "\n"
                + "idFornecedor: " + ultimaVenda.getFornecedor().getIdFornecedor() + "\n"
                + "valorVenda: " + Double.parseDouble(this.tfSubTotal.getText().replace(",", "."))
                + "\n-------------------------------------------------\n\n");

        java.util.Date utilDate = compra.getDataCompra();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        String data = "'" + sqlDate + "'";

        String SQL = "UPDATE compra "
                + "SET data_compra = " + data + ","
                + " valor_compra = " + compra.getValorCompra() + ","
                + " quant_parcela = " + compra.getQuantParcela() + ","
                + " cod_fornecedor = " + compra.getFornecedor().getIdFornecedor()
                + " WHERE cod_compra = " + compra.getIdCompra();

        System.out.print(SQL + "\n\n");

        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddItem;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btFolderFornecedor;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btParcelamento;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSearchProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbParcelamento;
    private javax.swing.JTable tbItemCompra;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCelular;
    private javax.swing.JTextField tfCep;
    private javax.swing.JTextField tfCodigoCidade;
    private javax.swing.JTextField tfCodigoFornecedor;
    private javax.swing.JTextField tfCodigoProduto;
    private javax.swing.JTextField tfCpfCnpj;
    private javax.swing.JFormattedTextField tfDataCompra;
    private javax.swing.JTextField tfDesconto;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNomeCidade;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfQuantParcela;
    private javax.swing.JTextField tfQuantidade;
    private javax.swing.JTextField tfRgInscricao;
    private javax.swing.JTextField tfSubDesconto;
    private javax.swing.JTextField tfSubTotal;
    private javax.swing.JTextField tfTelefone;
    private javax.swing.JTextField tfUfCidade;
    private javax.swing.JTextField tfValorCompra;
    private javax.swing.JTextField tfValorItem;
    // End of variables declaration//GEN-END:variables
    private List<ItemCompra> itens = new ArrayList<>();
    private List<TituloCompra> titulos = new ArrayList<>();

}
