package br.com.pitanga.view;

import br.com.pitanga.dao.DAOFactory;
import br.com.pitanga.dao.model.ItemVendaDAO;
import br.com.pitanga.dao.model.TituloVendaDAO;
import br.com.pitanga.dao.model.VendaDAO;
import br.com.pitanga.domain.ItemVenda;
import br.com.pitanga.domain.TituloVenda;
import br.com.pitanga.domain.Venda;
import br.com.pitanga.table.model.ItemVendaTableModel;
import br.com.pitanga.table.model.TituloVendaTableModel;
import br.com.pitanga.util.GUIUtils;
import br.com.pitanga.util.StringUtils;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Douglas Gusson
 */
public class FrmConfirmaExclusaoVenda extends javax.swing.JDialog {

    private Venda venda;
    private List<ItemVenda> itens = new ArrayList<>();
    private List<TituloVenda> titulos = new ArrayList<>();

    /**
     * Creates new form FrmConfirmaExclusaoProduto
     *
     * @param parent
     * @param modal
     * @param venda
     */
    public FrmConfirmaExclusaoVenda(JDialog parent,
            boolean modal, Venda venda) {
        super(parent, modal);

        initComponents();
        initialize();
        this.venda = venda;
        setVenda(this.venda);
    }

    private void setVenda(Venda v) {
        tfCodigoVenda.setText(StringUtils.inteiroCincoDig(v.getIdVenda()));
        tfDataVenda.setDate(v.getDataVenda());
        tfValor.setText(StringUtils.formatarDecimal(v.getValorVenda()));
        tfNomeCliente.setText(v.getCliente().getNome());

        ItemVendaDAO itemVendaDAO = DAOFactory.getDefaultDAOFactory().getItemVendaDAO();
        TituloVendaDAO tituloVendaDAO = DAOFactory.getDefaultDAOFactory().getTituloVendaDAO();
        itens = itemVendaDAO.listarPorVenda(venda.getIdVenda());
        tbItemVenda.setModel(new ItemVendaTableModel(itens));
        titulos = tituloVendaDAO.listarPorVenda(venda.getIdVenda());
        tbTituloVenda.setModel(new TituloVendaTableModel(titulos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNao = new javax.swing.JButton();
        btSim = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNomeCliente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTituloVenda = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItemVenda = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfCodigoVenda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfDataVenda = new com.toedter.calendar.JDateChooser();
        tfValor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btNao.setText("Sair");
        btNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNaoActionPerformed(evt);
            }
        });

        btSim.setText("Excluir");
        btSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Cliente:");

        tfNomeCliente.setForeground(new java.awt.Color(0, 0, 0));
        tfNomeCliente.setEnabled(false);
        tfNomeCliente.setFocusable(false);

        tbTituloVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbTituloVenda.setEnabled(false);
        tbTituloVenda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbTituloVenda.getTableHeader().setResizingAllowed(false);
        tbTituloVenda.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbTituloVenda);

        tbItemVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbItemVenda.setEnabled(false);
        tbItemVenda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbItemVenda.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbItemVenda);

        jLabel2.setText("Itens:");

        jLabel4.setText("Títulos:");

        tfCodigoVenda.setForeground(new java.awt.Color(0, 0, 0));
        tfCodigoVenda.setEnabled(false);

        jLabel5.setText("Cód. Venda:");

        jLabel6.setText("Data:");

        tfDataVenda.setBackground(new java.awt.Color(255, 255, 255));
        tfDataVenda.setForeground(new java.awt.Color(255, 255, 255));
        tfDataVenda.setEnabled(false);

        tfValor.setForeground(new java.awt.Color(0, 0, 0));
        tfValor.setEnabled(false);

        jLabel7.setText("Valor (R$):");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNomeCliente)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(tfDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btNao)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSim)
                    .addComponent(btNao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNaoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btNaoActionPerformed

    private void btSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimActionPerformed
        int i = JOptionPane.showConfirmDialog(null,
                "Deseja mesmo excluir?\n\n"
                + "Atenção: esta ação removerá também todos os títulos \n"
                + "e todos os itens associados a essa venda.",
                "Excluir", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            VendaDAO vendaDAO = DAOFactory.getDefaultDAOFactory().getVendaDAO();
            if (vendaDAO.remover(venda.getIdVenda())) {
                JOptionPane.showMessageDialog(null, "Venda removida!");
                this.dispose();
            }
        }
    }//GEN-LAST:event_btSimActionPerformed

    private void initialize() {
        this.setTitle("Pitanga System - Confirmação de Exclusão");
        GUIUtils.considerarEnterComoTab(this);
        // Se teclarmos ESC nesta janela, ela irá se fechar:  
        this.getRootPane().registerKeyboardAction((ActionEvent e) -> {
            FrmConfirmaExclusaoVenda.this.dispose();
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNao;
    private javax.swing.JButton btSim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbItemVenda;
    private javax.swing.JTable tbTituloVenda;
    private javax.swing.JTextField tfCodigoVenda;
    private com.toedter.calendar.JDateChooser tfDataVenda;
    private javax.swing.JTextField tfNomeCliente;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
