/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pitanga.view;

import br.com.pitanga.dao.model.CidadeDAO;
import br.com.pitanga.dao.model.FornecedorDAO;
import br.com.pitanga.domain.Cidade;
import br.com.pitanga.domain.Fornecedor;
import br.com.pitanga.table.cellrenderer.FornecedorCellRenderer;
import br.com.pitanga.table.model.FornecedorTableModel;
import br.com.pitanga.dao.DAOFactory;
import br.com.pitanga.util.GUIUtils;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Douglas Gusson
 */
public class FrmFornecedor extends javax.swing.JDialog {

    List<Fornecedor> fornecedores = null;
    List<Cidade> cidades = null;

    /**
     * Creates new form FrmCliente
     *
     * @param parent
     * @param modal
     */
    public FrmFornecedor(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbFornecedor = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCpfCnpj = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfRgInscricao = new javax.swing.JTextField();
        btNovo = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        tfCelular = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfCep = new javax.swing.JTextField();
        lbCodigo = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfCodigoCidade = new javax.swing.JTextField();
        btFolderCidade = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tfNomeCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfUfCidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfPesquisa = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btVisualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        setResizable(false);

        tbFornecedor.setAutoscrolls(false);
        tbFornecedor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbFornecedor);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");

        jLabel3.setText("CPF/CNPJ:");

        jLabel4.setText("RG/Insc.:");

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        jLabel6.setText("Número:");

        jLabel7.setText("Bairro:");

        jLabel8.setText("Telefone:");

        jLabel9.setText("Celular:");

        jLabel10.setText("E-mail:");

        jLabel11.setText("CEP:");

        lbCodigo.setText("Cod.:");

        tfCodigo.setEditable(false);
        tfCodigo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tfCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfCodigo.setFocusable(false);

        jLabel14.setText("Cod. cidade:");

        tfCodigoCidade.setEditable(false);
        tfCodigoCidade.setBackground(new java.awt.Color(255, 255, 255));
        tfCodigoCidade.setFocusable(false);

        btFolderCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pitanga/img/folder_16x16.png"))); // NOI18N
        btFolderCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFolderCidadeActionPerformed(evt);
            }
        });

        jLabel13.setText("Cidade:");

        tfNomeCidade.setEditable(false);
        tfNomeCidade.setBackground(new java.awt.Color(255, 255, 255));
        tfNomeCidade.setFocusable(false);

        jLabel12.setText("UF:");

        tfUfCidade.setEditable(false);
        tfUfCidade.setBackground(new java.awt.Color(255, 255, 255));
        tfUfCidade.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfNome, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(tfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(83, 83, 83))
                                    .addComponent(tfRgInscricao)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(tfBairro)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbCodigo)
                                .addGap(4, 4, 4)
                                .addComponent(tfCodigo))
                            .addComponent(tfTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfCep)
                                .addComponent(jLabel11)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(tfEmail)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfCodigoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btFolderCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(tfNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfUfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btGravar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btNovo)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfRgInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btFolderCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfCodigoCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfUfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btNovo)
                            .addComponent(btCancelar)
                            .addComponent(btGravar))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCodigo)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel5.setText("Pesquisa:");

        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyTyped(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btVisualizar.setText("Visualizar");
        btVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btSair))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btVisualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPesquisa)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir)
                    .addComponent(btAlterar)
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVisualizar)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        acaoNovo();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        inicializarFrame();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        // TODO add your handling code here:
        if (this.tfCodigo.getText().equals("")) {
            acaoGravar();
        } else {
            acaoGravarAlteracoes();
        }
    }//GEN-LAST:event_btGravarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        acaoExluir();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        acaoAlterar();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarActionPerformed
        // TODO add your handling code here:
        acaoVisualizar();
    }//GEN-LAST:event_btVisualizarActionPerformed

    private void tfPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyTyped
        // TODO add your handling code here:
        String termo = this.tfPesquisa.getText();
        preencherTabelaPesquisa(termo);
    }//GEN-LAST:event_tfPesquisaKeyTyped

    private void btFolderCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFolderCidadeActionPerformed
        FrmBuscaCidade obj = new FrmBuscaCidade(this, true, this);
        obj.setVisible(true);
    }//GEN-LAST:event_btFolderCidadeActionPerformed

    public void setCidade(Cidade cidade) {
        this.tfCodigoCidade.setText("" + cidade.getIdCidade());
        this.tfNomeCidade.setText(cidade.getNomeCidade());
        this.tfUfCidade.setText(cidade.getUf());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFolderCidade;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JTable tbFornecedor;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCelular;
    private javax.swing.JTextField tfCep;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCodigoCidade;
    private javax.swing.JTextField tfCpfCnpj;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNomeCidade;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfPesquisa;
    private javax.swing.JTextField tfRgInscricao;
    private javax.swing.JTextField tfTelefone;
    private javax.swing.JTextField tfUfCidade;
    // End of variables declaration//GEN-END:variables

    private void preencherTabela() {
        this.fornecedores = preencherFornecedores();
        if (this.fornecedores != null) {
            this.tbFornecedor.setModel(new FornecedorTableModel(this.fornecedores));
            this.tbFornecedor.setDefaultRenderer(Object.class, new FornecedorCellRenderer());
        }
    }

    private void preencherTabelaPesquisa(String nome) {
        FornecedorDAO cd = DAOFactory.getDefaultDAOFactory().getFornecedorDAO();
        this.fornecedores = cd.buscarPorNome(nome);
        if (this.fornecedores != null) {
            tbFornecedor.setModel(new FornecedorTableModel(this.fornecedores));
            tbFornecedor.setDefaultRenderer(Object.class, new FornecedorCellRenderer());
        }
    }

    private void acaoNovo() {
        // Botões
        this.btAlterar.setEnabled(false);
        this.btExcluir.setEnabled(false);
        this.btVisualizar.setEnabled(false);
        this.btNovo.setEnabled(false);
        this.btCancelar.setEnabled(true);
        this.btGravar.setEnabled(true);
        // Tabela
        this.tbFornecedor.setEnabled(false);
        this.tbFornecedor.setRowSelectionAllowed(false);
        // Campos
        this.tfPesquisa.setEnabled(false);
        this.tfNome.setEnabled(true);
        this.tfCpfCnpj.setEnabled(true);
        this.tfRgInscricao.setEnabled(true);
        this.tfEndereco.setEnabled(true);
        this.tfNumero.setEnabled(true);
        this.tfBairro.setEnabled(true);
        this.tfCep.setEnabled(true);
        this.tfTelefone.setEnabled(true);
        this.tfCelular.setEnabled(true);
        this.tfEmail.setEnabled(true);
        // Setar foco
        this.tfNome.requestFocus();
    }

    private void acaoGravar() {

        if ((this.tfNome.getText().trim()).equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Favor informar o nome do fornecedor!",
                    "Campo obrigatório", JOptionPane.INFORMATION_MESSAGE);
            this.tfNome.requestFocus();
        } else if (this.tfCodigoCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Favor informar a cidade do fornecedor!",
                    "Campo obrigatório", JOptionPane.INFORMATION_MESSAGE);
            this.btFolderCidade.requestFocus();
        } else {
            Fornecedor fornecedor = new Fornecedor();
            Cidade cidade = new Cidade();

            fornecedor.setNomeFornecedor(this.tfNome.getText().trim());
            fornecedor.setCpfCnpjFornecedor(this.tfCpfCnpj.getText().trim());
            fornecedor.setRgFornecedor(this.tfRgInscricao.getText().trim());
            fornecedor.setEnderecoFornecedor(this.tfEndereco.getText().trim());
            fornecedor.setNumeroFornecedor(this.tfNumero.getText().trim());
            fornecedor.setBairroFornecedor(this.tfBairro.getText().trim());
            fornecedor.setCepFornecedor(this.tfCep.getText().trim());
            cidade.setIdCidade(Integer.parseInt(this.tfCodigoCidade.getText().trim()));
            fornecedor.setCidade(cidade);
            fornecedor.setTelefoneFornecedor(this.tfTelefone.getText().trim());
            fornecedor.setCelularFornecedor(this.tfCelular.getText().trim());
            fornecedor.setEmailFornecedor(this.tfEmail.getText().trim());

            FornecedorDAO forDao = DAOFactory.getDefaultDAOFactory().getFornecedorDAO();
            forDao.inserir(fornecedor);

            inicializarFrame();
        }
    }

    private void acaoExluir() {

        int selecionada = -1;
        selecionada = this.tbFornecedor.getSelectedRow();

        if (selecionada == -1) {
            JOptionPane.showMessageDialog(rootPane,
                    "- NENHUM FORNECEDOR SELECIONADO -",
                    "Pitanga System - EXCLUIR",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {

            Fornecedor forn = new Fornecedor();

            if (this.fornecedores != null) {
                FornecedorTableModel tableModel = new FornecedorTableModel(this.fornecedores);
                forn = tableModel.get(selecionada);
            }

            int codigo = forn.getIdFornecedor();
            String nome = forn.getNomeFornecedor();
            String cpf = forn.getCpfCnpjFornecedor();

            int i = JOptionPane.showConfirmDialog(null,
                    "DESEJA MESMO EXCLIUR O FORNECEDOR ABAIXO?\n\n"
                    + "Código: " + codigo
                    + "\nNome: " + nome
                    + "\nCPF/CNPJ: " + cpf + "\n\n",
                    "Pitanga System - Confirmação de exclusão",
                    JOptionPane.YES_NO_OPTION);
            if (i == JOptionPane.YES_OPTION) {
                FornecedorDAO fd = DAOFactory.getDefaultDAOFactory().getFornecedorDAO();
                fd.remover(codigo);
            }
        }
        inicializarFrame();
    }

    private void acaoAlterar() {
        int selecionada = -1;
        selecionada = this.tbFornecedor.getSelectedRow();

        if (selecionada == -1) {
            JOptionPane.showMessageDialog(rootPane,
                    "- NENHUM FORNECEDOR SELECIONADO -",
                    "Pitanga System - ALTERAR",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            Fornecedor obj = new Fornecedor();
            if (this.fornecedores != null) {
                FornecedorTableModel tableModel = new FornecedorTableModel(this.fornecedores);
                obj = tableModel.get(selecionada);
            }

            FornecedorDAO forDao = DAOFactory.getDefaultDAOFactory().getFornecedorDAO();
            Fornecedor forn = forDao.buscar(obj.getIdFornecedor());

            acaoNovo();
            this.tfCodigo.setVisible(true);
            this.lbCodigo.setVisible(true);
            this.btGravar.setEnabled(true);
            this.btAlterar.setEnabled(false);
            this.btExcluir.setEnabled(false);
            this.btVisualizar.setEnabled(false);
            this.tfPesquisa.setEnabled(false);
            this.tbFornecedor.setEnabled(false);
            this.tfNome.setText(forn.getNomeFornecedor());
            this.tfCpfCnpj.setText(forn.getCpfCnpjFornecedor());
            this.tfRgInscricao.setText(forn.getRgFornecedor());
            this.tfEndereco.setText(forn.getEnderecoFornecedor());
            this.tfNumero.setText(forn.getNumeroFornecedor());
            this.tfBairro.setText(forn.getBairroFornecedor());
            this.tfCep.setText(forn.getCepFornecedor());

            this.tfTelefone.setText(forn.getTelefoneFornecedor());
            this.tfCelular.setText(forn.getCelularFornecedor());
            this.tfEmail.setText(forn.getEmailFornecedor());
            this.tfCodigo.setText("" + forn.getIdFornecedor());
        }
    }

    private void acaoGravarAlteracoes() {

        Fornecedor fornecedor = new Fornecedor();
        Cidade cidade = new Cidade();

        fornecedor.setNomeFornecedor(this.tfNome.getText().trim());
        fornecedor.setCpfCnpjFornecedor(this.tfCpfCnpj.getText().trim());
        fornecedor.setRgFornecedor(this.tfRgInscricao.getText().trim());
        fornecedor.setEnderecoFornecedor(this.tfEndereco.getText().trim());
        fornecedor.setNumeroFornecedor(this.tfNumero.getText().trim());
        fornecedor.setBairroFornecedor(this.tfBairro.getText().trim());
        fornecedor.setCepFornecedor(this.tfCep.getText().trim());

        //capturar o código da cidade  
        int idCidade = 0;
        List<Cidade> lista = new ArrayList<>();
        CidadeDAO cd = DAOFactory.getDefaultDAOFactory().getCidadeDAO();
        lista = cd.listar();
//        for (Cidade c : lista) {
//            if ((this.cbCidade.getSelectedItem().toString()).equals(
//                    c.getNome() + " (" + c.getCodigo() + ")")) {
//                idCidade = c.getCodigo();
//                cidade.setCodigo(idCidade);
//                fornecedor.setCidade(cidade);
//            }
//        }
        cidade.setIdCidade(idCidade);
        fornecedor.setCidade(cidade);

        fornecedor.setTelefoneFornecedor(this.tfTelefone.getText().trim());
        fornecedor.setCelularFornecedor(this.tfCelular.getText().trim());
        fornecedor.setEmailFornecedor(this.tfEmail.getText().trim());
        fornecedor.setIdFornecedor(Integer.parseInt(this.tfCodigo.getText()));

        FornecedorDAO forDao = DAOFactory.getDefaultDAOFactory().getFornecedorDAO();
        forDao.alterar(fornecedor);
        inicializarFrame();
    }

    private void acaoVisualizar() {
        int selecionada = -1;

        selecionada = this.tbFornecedor.getSelectedRow();

        if (selecionada == -1) {
            JOptionPane.showMessageDialog(rootPane,
                    "- NENHUM FORNECEDOR SELECIONADO -",
                    "Pitanga System - VISUALIZAR",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            Fornecedor forn = new Fornecedor();
            if (this.fornecedores != null) {
                FornecedorTableModel tableModel = new FornecedorTableModel(this.fornecedores);
                forn = tableModel.get(selecionada);
            }

            int codigo = forn.getIdFornecedor();

            FornecedorDAO cd = DAOFactory.getDefaultDAOFactory().getFornecedorDAO();
            Fornecedor obj = cd.buscar(codigo);

            JOptionPane.showMessageDialog(rootPane,
                    "___________________________________________________________"
                    + "_________________________________________________________"
                    + "\nCódigo: " + obj.getIdFornecedor()
                    + "\nNome: " + obj.getNomeFornecedor()
                    + "\nCPF/CNPJ: " + obj.getCpfCnpjFornecedor()
                    + "\nRG/Insc.: " + obj.getRgFornecedor()
                    + "\nEndereço: " + obj.getEnderecoFornecedor()
                    + "\n_________________________________________________________"
                    + "___________________________________________________________",
                    "Pitanga System - Visualizar fornecedor: " + obj.getNomeFornecedor(), JOptionPane.DEFAULT_OPTION);

        }
    }

    private void inicializarFrame() {
        // Preenche a tabela de clientes
        preencherTabela();
        // Preenche listas
        this.cidades = preencherCidades();
        this.fornecedores = preencherFornecedores();
        // Habilita o campo de pesquisa
        this.tfPesquisa.setEnabled(true);
        // Habilita a tabela de clientes
        this.tbFornecedor.setEnabled(true);
        // Habilita a seleção na tabela
        this.tbFornecedor.setRowSelectionAllowed(true);
        // Habilita/desabilita os botões
        this.btNovo.setEnabled(true);
        this.btCancelar.setEnabled(false);
        this.btGravar.setEnabled(false);
        this.btAlterar.setEnabled(true);
        this.btExcluir.setEnabled(true);
        this.btVisualizar.setEnabled(true);
        // Desabilita os campos        
        this.tfCodigo.setVisible(false);
        this.lbCodigo.setVisible(false);
        this.tfNome.setEnabled(false);
        this.tfCpfCnpj.setEnabled(false);
        this.tfRgInscricao.setEnabled(false);
        this.tfEndereco.setEnabled(false);
        this.tfNumero.setEnabled(false);
        this.tfBairro.setEnabled(false);
        this.tfCep.setEnabled(false);
        this.tfCodigoCidade.setEnabled(false);
        this.tfNomeCidade.setEnabled(false);
        this.tfUfCidade.setEnabled(false);
        this.tfTelefone.setEnabled(false);
        this.tfCelular.setEnabled(false);
        this.tfEmail.setEnabled(false);
        // Limpa os campos
        this.tfCodigo.setText("");
        this.tfNome.setText("");
        this.tfEndereco.setText("");
        this.tfNumero.setText("");
        this.tfBairro.setText("");
        this.tfCep.setText("");
        this.tfCodigoCidade.setText("");
        this.tfNomeCidade.setText("");
        this.tfUfCidade.setText("");
        this.tfCpfCnpj.setText("");
        this.tfRgInscricao.setText("");
        this.tfTelefone.setText("");
        this.tfCelular.setText("");
        this.tfEmail.setText("");
        this.tfPesquisa.setText("");
        this.setTitle("Pitanga System - Fornecedores");
        GUIUtils.considerarEnterComoTab(this);
    }

    private List<Cidade> preencherCidades() {
        List<Cidade> lista = new ArrayList<>();
        CidadeDAO cd = DAOFactory.getDefaultDAOFactory().getCidadeDAO();
        lista = cd.listar();

        return lista;
    }

    private List<Fornecedor> preencherFornecedores() {
        List<Fornecedor> lista = new ArrayList<>();
        FornecedorDAO fd = DAOFactory.getDefaultDAOFactory().getFornecedorDAO();
        lista = fd.listarTodos();

        return lista;
    }

}
