package br.com.pitanga.view;

import br.com.pitanga.dao.DAOFactory;
import br.com.pitanga.dao.model.ProdutoDAO;
import br.com.pitanga.dao.model.RelatorioDAO;
import br.com.pitanga.domain.Produto;
import br.com.pitanga.util.StringUtils;
import java.util.Calendar;
import javax.swing.JFrame;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
public class FrmListagemProdutoVenda extends javax.swing.JDialog {

    private Produto produto;

    /**
     * Creates new form TesteJDialog
     *
     * @param parent
     * @param modal
     */
    public FrmListagemProdutoVenda(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfDataInicio = new com.toedter.calendar.JDateChooser();
        tfDataFim = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfCodigoProduto = new javax.swing.JTextField();
        btSearchProduto = new javax.swing.JButton();
        tfDescricao = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Data inicial:");

        jLabel2.setText("Data final:");

        jLabel15.setText("Produto:");

        tfCodigoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCodigoProdutoFocusLost(evt);
            }
        });
        tfCodigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCodigoProdutoKeyTyped(evt);
            }
        });

        btSearchProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pitanga/img/pesquisa_16x16.png"))); // NOI18N
        btSearchProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchProdutoActionPerformed(evt);
            }
        });

        tfDescricao.setEditable(false);

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Visualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(tfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btSearchProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2)
                        .addComponent(tfDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSearchProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(tfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(tfDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodigoProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodigoProdutoFocusLost
        if (!tfCodigoProduto.getText().isEmpty()) {
            ProdutoDAO pd = DAOFactory.getDefaultDAOFactory().getProdutoDAO();
            produto = pd.buscar(Integer.parseInt(this.tfCodigoProduto.getText()));
            setProduto(produto);
        } else if ((this.tfCodigoProduto.getText().trim()).equals("00000")) {
            FrmBuscaProduto frmBuscaProduto = new FrmBuscaProduto(this, this);
            frmBuscaProduto.setVisible(true);
        }
    }//GEN-LAST:event_tfCodigoProdutoFocusLost

    private void tfCodigoProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoProdutoKeyTyped
        StringUtils obj = new StringUtils();
        obj.somenteNumeros(evt, this);
    }//GEN-LAST:event_tfCodigoProdutoKeyTyped

    private void btSearchProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchProdutoActionPerformed
        FrmBuscaProduto obj = new FrmBuscaProduto(this, this);
        obj.setVisible(true);
    }//GEN-LAST:event_btSearchProdutoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        RelatorioDAO obj = DAOFactory.getDefaultDAOFactory().getRelatorioDAO();

        Calendar dataInicial = tfDataInicio.getCalendar();
        Calendar dataFinal = tfDataFim.getCalendar();

        JasperViewer jv = obj.gerarRelatorioVendaProduto(produto, dataInicial, dataFinal);

        FrmReport frmReport = new FrmReport(this, "tetettete", true, jv);
        frmReport.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void setProduto(Produto produto) {
        this.tfCodigoProduto.setText(String.format("%05d", produto.getIdProduto()));
        this.tfDescricao.setText(produto.getDescricao());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSearchProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfCodigoProduto;
    private com.toedter.calendar.JDateChooser tfDataFim;
    private com.toedter.calendar.JDateChooser tfDataInicio;
    private javax.swing.JTextField tfDescricao;
    // End of variables declaration//GEN-END:variables
}
