package br.com.pitanga.view;

import br.com.pitanga.dao.DAOFactory;
import br.com.pitanga.dao.model.FormaPagamentoDAO;
import br.com.pitanga.dao.model.RecebimentoDAO;
import br.com.pitanga.dao.model.TituloVendaDAO;
import br.com.pitanga.domain.FormaPagamento;
import br.com.pitanga.domain.Recebimento;
import br.com.pitanga.domain.TituloVenda;
import br.com.pitanga.util.GUIUtils;
import br.com.pitanga.util.StringUtils;
import java.util.Date;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.joda.time.DateTime;
import org.joda.time.Days;

/**
 *
 * @author Douglas Gusson
 */
public class FrmRecebimento extends javax.swing.JDialog {

    private TituloVenda titulo;
    private List<FormaPagamento> formas;

    /**
     * Creates new form FrmRecebimento
     *
     * @param titulo
     * @param parent
     * @param modal
     */
    public FrmRecebimento(TituloVenda titulo, JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.titulo = titulo;
        inicializarFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        tfCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfParcela = new javax.swing.JTextField();
        tfValorParcela = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfCodVenda = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfValorRecebido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfJuros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfMulta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbFormaPagamento = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taObservacoes = new javax.swing.JTextArea();
        lblAtraso = new javax.swing.JLabel();
        tfDataRecebimento = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        tfDesconto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfVencimento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        tfCliente.setEditable(false);
        tfCliente.setFocusable(false);

        jLabel7.setText("Cliente:");

        tfParcela.setEditable(false);
        tfParcela.setFocusable(false);

        tfValorParcela.setEditable(false);
        tfValorParcela.setFocusable(false);

        jLabel8.setText("Parcela:");

        jLabel9.setText("Valor (R$):");

        jLabel10.setText("Cod. Venda:");

        tfCodVenda.setEditable(false);
        tfCodVenda.setFocusable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Recebimento"));

        jLabel2.setText("Data:");

        jLabel3.setText("Valor recebido:");

        tfValorRecebido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfValorRecebidoFocusLost(evt);
            }
        });

        jLabel5.setText("Juros:");

        tfJuros.setText("0,00");

        jLabel4.setText("Desconto:");

        tfMulta.setText("0,00");

        jLabel1.setText("Forma de Pagamento:");

        cbFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cheque", "Dinheiro" }));

        jLabel6.setText("Observações:");

        taObservacoes.setColumns(20);
        taObservacoes.setRows(5);
        jScrollPane1.setViewportView(taObservacoes);

        lblAtraso.setForeground(java.awt.Color.blue);
        lblAtraso.setText("jLabel12");

        tfDataRecebimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDataRecebimentoFocusLost(evt);
            }
        });

        jLabel12.setText("Multa:");

        tfDesconto.setText("0,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAtraso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbFormaPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(tfDataRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(tfJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfDataRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAtraso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("Vencimento:");

        tfVencimento.setEditable(false);
        tfVencimento.setFocusable(false);

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCliente)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfVencimento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(tfValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(5, 5, 5)
                                    .addComponent(tfParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(5, 5, 5)
                                    .addComponent(tfCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(5, 5, 5)
                                .addComponent(tfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(5, 5, 5)
                        .addComponent(tfValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void tfDataRecebimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDataRecebimentoFocusLost

    }//GEN-LAST:event_tfDataRecebimentoFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gravarRecebimento();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfValorRecebidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfValorRecebidoFocusLost
        valorRecebido();
    }//GEN-LAST:event_tfValorRecebidoFocusLost

    private void valorRecebido() {
        double valorRecebido = Double.parseDouble(tfValorRecebido.getText().replace(",", "."));
        double valorAberto = (titulo.getValorParcela() - titulo.getValorRecebido());
        if (valorRecebido > valorAberto) {
            JOptionPane.showMessageDialog(null,
                    "O valor recebido não pode ser "
                    + "\nmaior que o valor em aberto."
                    + "\n\nTotal em aberto: R$ " + StringUtils.formatarDecimal(valorAberto));
            tfValorRecebido.setText(StringUtils.formatarDecimal(valorAberto));
            tfValorRecebido.requestFocus();
        } else if (valorRecebido < 0) {
            JOptionPane.showMessageDialog(null,
                    "O valor recebido não pode ser menor que zero.");
            tfValorRecebido.requestFocus();
            tfValorRecebido.setText("0,00");
        }
    }

    private void inicializarFrame() {
//      tfDataRecebimentoLostFocus();
        cbFormaPagamento.removeAllItems();
        if (preencherFormasPagamento()) {
            cbFormaPagamento.setSelectedIndex(0);
        }
        lblAtraso.setText("");
        tfCliente.setText(titulo.getVenda().getCliente().getNome());
        tfCodVenda.setText(StringUtils.inteiroCincoDig(titulo.getVenda().getIdVenda()));
        tfParcela.setText(StringUtils.inteiroDoisDig(titulo.getNumParcela()) + " / "
                + StringUtils.inteiroDoisDig(titulo.getVenda().getQuantParcela()));
        tfVencimento.setText(StringUtils.formataData(titulo.getVencimento()));
        tfValorParcela.setText(StringUtils.formatarDecimal(titulo.getValorParcela()));
        tfValorRecebido.setText(StringUtils.formatarDecimal(
                titulo.getValorParcela() - titulo.getValorRecebido()));
        this.setTitle("Pitanga System - Recebimento");
        GUIUtils obj = new GUIUtils();
        GUIUtils.considerarEnterComoTab(this);
        this.tfDataRecebimento.setDate(new Date());
    }

    private void gravarRecebimento() {
        Recebimento recebimento = new Recebimento();
        FormaPagamento formaPagamento = formas.get(cbFormaPagamento.getSelectedIndex());
        recebimento.setFormaPagamento(formaPagamento);
        recebimento.setTituloVenda(titulo);
        recebimento.setDataRecebimento(tfDataRecebimento.getDate());
        recebimento.setValor(Double.parseDouble(tfValorRecebido.getText().replace(",", ".")));
        recebimento.setDesconto(Double.parseDouble(tfDesconto.getText().replace(",", ".")));
        recebimento.setMulta(Double.parseDouble(tfMulta.getText().replace(",", ".")));
        recebimento.setJuros(Double.parseDouble(tfJuros.getText().replace(",", ".")));
        recebimento.setObservacoes(taObservacoes.getText());

        RecebimentoDAO recebimentoDAO = DAOFactory.getDefaultDAOFactory().getRecebimentoDAO();
        TituloVendaDAO tituloVendaDAO = DAOFactory.getDefaultDAOFactory().getTituloVendaDAO();
        if (recebimentoDAO.inserir(recebimento)) {
            titulo.setValorRecebido(recebimento.getValor());
            tituloVendaDAO.atualizarRecebimentoTitulo(titulo);
            JOptionPane.showMessageDialog(null, "Baixa registrada!");
            this.dispose();
        }
    }

    private boolean preencherFormasPagamento() {
        FormaPagamentoDAO formaDao = DAOFactory.getDefaultDAOFactory().getFormaPagamentoDAO();
        formas = formaDao.listarTodos();

        if (!formas.isEmpty()) {
            for (FormaPagamento item : formas) {
                cbFormaPagamento.addItem(item.getDescricao());
            }
            return true;
        }
        return false;
    }

    private void verificaAtraso(DateTime vencimento, DateTime recebimento) {

        System.out.print(vencimento);

        int dias = Days.daysBetween(vencimento, recebimento).getDays();
        if (dias > 0) {
            if (dias == 1) {
                lblAtraso.setText(dias + " dia de atraso.");
            } else {
                lblAtraso.setText(dias + " dias de atraso.");
            }
        } else if (dias < 0) {
            if (Math.abs(dias) == 1) {
                lblAtraso.setText(Math.abs(dias) + " dia de antecipação.");
            } else {
                lblAtraso.setText(Math.abs(dias) + " dias de antecipação.");
            }
        } else {
            lblAtraso.setText("");
        }
    }

//                DateTime vencimento = new DateTime(titulo.getVencimento());
//                DateTime recebimento = new DateTime(tfDataRecebimento.getDate());
//
//                verificaAtraso(vencimento, recebimento);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox cbFormaPagamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtraso;
    private javax.swing.JTextArea taObservacoes;
    private javax.swing.JTextField tfCliente;
    private javax.swing.JTextField tfCodVenda;
    private com.toedter.calendar.JDateChooser tfDataRecebimento;
    private javax.swing.JTextField tfDesconto;
    private javax.swing.JTextField tfJuros;
    private javax.swing.JTextField tfMulta;
    private javax.swing.JTextField tfParcela;
    private javax.swing.JTextField tfValorParcela;
    private javax.swing.JTextField tfValorRecebido;
    private javax.swing.JTextField tfVencimento;
    // End of variables declaration//GEN-END:variables
}
