/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pitanga.view;

import br.com.pitanga.domain.TituloCompra;
import br.com.pitanga.table.model.TituloCompraTableModel;
import br.com.pitanga.util.GUIUtils;
import br.com.pitanga.util.StringUtils;
import java.awt.Window;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Netsul
 */
public class FrmTituloCompra extends javax.swing.JDialog {

    /**
     * Creates new form FrmTituloCompra
     *
     * @param owner
     * @param modal
     * @param titulos
     * @param valorVenda
     * @param parcelamento
     * @param dataVenda
     * @param quantParcela
     */
    public FrmTituloCompra(Window owner, boolean modal, List<TituloCompra> titulos, double valorVenda,
            Date dataVenda, JLabel parcelamento, JTextField quantParcela) {
        super(owner, DEFAULT_MODALITY_TYPE);
        initComponents();
        inicialiarFrame();

        this.titulos = titulos;
        this.valorVenda = valorVenda;
        this.dataVenda = dataVenda;
        this.parcelamento = parcelamento;
        this.quantParcela = quantParcela;

        this.tbTituloCompra.setModel(new TituloCompraTableModel(titulos));

    }

    public FrmTituloCompra() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTituloCompra = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        tfVencimento = new javax.swing.JFormattedTextField();
        btLimpar = new javax.swing.JButton();
        btOk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfParcela = new javax.swing.JTextField();
        btAlterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfQuantParcelas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPrazo = new javax.swing.JTextField();
        btCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbTituloCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbTituloCompra.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbTituloCompra.getTableHeader().setResizingAllowed(false);
        tbTituloCompra.getTableHeader().setReorderingAllowed(false);
        tbTituloCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTituloCompraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTituloCompra);

        jLabel3.setText("Valor:");

        jLabel4.setText("Vencimento:");

        try {
            tfVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        jLabel5.setText("Parcela:");

        tfParcela.setEditable(false);
        tfParcela.setFocusable(false);

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));

        jLabel1.setText("Quant. Parcelas:");

        tfQuantParcelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfQuantParcelasKeyTyped(evt);
            }
        });

        jLabel2.setText("Prazo:");

        tfPrazo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPrazoKeyTyped(evt);
            }
        });

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfQuantParcelas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCalcular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfQuantParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCalcular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btOk))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btAlterar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAlterar)
                            .addComponent(tfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLimpar)
                    .addComponent(btOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbTituloCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTituloCompraMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int selecionada = tbTituloCompra.getSelectedRow();

            this.tfParcela.setText(this.tbTituloCompra.getValueAt(selecionada, 0).toString());
            this.tfValor.setText(this.tbTituloCompra.getValueAt(selecionada, 1).toString());
            SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
            this.tfVencimento.setText(formatador.format(this.tbTituloCompra.getValueAt(selecionada, 2)));

            this.tfValor.setEnabled(true);
            this.tfVencimento.setEnabled(true);
            this.btAlterar.setEnabled(true);

        }
    }//GEN-LAST:event_tbTituloCompraMouseClicked

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        this.titulos.removeAll(titulos);
        this.parcelamento.setText("Nenhuma parcela lançada.");
        this.tbTituloCompra.setModel(new TituloCompraTableModel(titulos));
    }//GEN-LAST:event_btLimparActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed

        if (!this.titulos.isEmpty()) {
            if (this.titulos.size() > 1) {
                this.parcelamento.setText(this.titulos.size() + " PARCELAS");
                this.quantParcela.setText("" + this.titulos.size());
            } else {
                this.parcelamento.setText(this.titulos.size() + " PARCELA");
                this.quantParcela.setText("" + this.titulos.size());
            }
        } else {
            this.parcelamento.setText("Nenhuma parcela lançada.");
        }
        this.dispose();
    }//GEN-LAST:event_btOkActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        this.tfParcela.setText(null);
        this.tfValor.setText(null);
        this.tfVencimento.setText(null);
        this.tfValor.setEnabled(false);
        this.tfVencimento.setEnabled(false);
        this.btAlterar.setEnabled(false);
    }//GEN-LAST:event_btAlterarActionPerformed

    private void tfQuantParcelasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantParcelasKeyTyped
        // TODO add your handling code here:
        strUtils.somenteNumeros(evt, this);
    }//GEN-LAST:event_tfQuantParcelasKeyTyped

    private void tfPrazoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrazoKeyTyped
        // TODO add your handling code here:
        strUtils.somenteNumeros(evt, this);
    }//GEN-LAST:event_tfPrazoKeyTyped

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        // TODO add your handling code here:
        if (!this.titulos.isEmpty()) {
            this.titulos.removeAll(titulos);
            this.tbTituloCompra.setModel(new TituloCompraTableModel(titulos));
            int quantParcelas = Integer.parseInt(this.tfQuantParcelas.getText());
            int prazo = Integer.parseInt(this.tfPrazo.getText());
            lancarParcelas(quantParcelas, prazo);
        } else {
            int quantParcelas = Integer.parseInt(this.tfQuantParcelas.getText());
            int prazo = Integer.parseInt(this.tfPrazo.getText());
            lancarParcelas(quantParcelas, prazo);
        }
    }//GEN-LAST:event_btCalcularActionPerformed

    private void inicialiarFrame() {

        this.tfValor.setEnabled(false);
        this.tfVencimento.setEnabled(false);
        this.btAlterar.setEnabled(false);

        this.tbTituloCompra.setNextFocusableComponent(this.btOk);
        // Seta o título para o frame
        this.setTitle("Pitanga System - Títulos");
        // Instancia a classe Complemento
        GUIUtils obj = new GUIUtils();
        // Habilita o Enter como TAB, passando o Componente
        obj.considerarEnterComoTab(this);
    }

    private void lancarParcelas(int quantParcela, int prazo) {

        double valorParcela = (valorVenda / quantParcela);

        Calendar c = Calendar.getInstance();
        c.setTime(dataVenda);

        for (int i = 0; i < quantParcela; i++) {

            c.add(Calendar.DATE, +prazo);
            Date vencimento = c.getTime();

            TituloCompra titulo = new TituloCompra();
            titulo.setNumParcela(i + 1);
            titulo.setValorParcela(valorParcela);
            titulo.setVencimento(vencimento);

            titulos.add(titulo);

        }

        this.tbTituloCompra.setModel(new TituloCompraTableModel(titulos));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTituloCompra;
    private javax.swing.JTextField tfParcela;
    private javax.swing.JTextField tfPrazo;
    private javax.swing.JTextField tfQuantParcelas;
    private javax.swing.JTextField tfValor;
    private javax.swing.JFormattedTextField tfVencimento;
    // End of variables declaration//GEN-END:variables
    private double valorVenda;
    private Date dataVenda;
    private JLabel parcelamento;
    private JTextField quantParcela;
    private List<TituloCompra> titulos = new ArrayList<>();
    private StringUtils strUtils = new StringUtils();

}
