package br.com.pitanga.view;

import br.com.pitanga.dao.model.UnidadeDAO;
import br.com.pitanga.domain.Unidade;
import br.com.pitanga.table.cellrenderer.UnidadeCellRenderer;
import br.com.pitanga.table.model.UnidadeTableModel;
import br.com.pitanga.util.GUIUtils;
import br.com.pitanga.dao.DAOFactory;
import java.util.List;
import br.com.pitanga.util.LimiteDigitos;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Douglas Gusson
 */
public class FrmUnidade extends javax.swing.JDialog {

    private List<Unidade> unidades;

    /**
     * Creates new form FrmUnidade
     *
     * @param parent
     * @param modal
     */
    public FrmUnidade(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfDescricao = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btNovo = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUnidade = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfPesquisa = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Cód. Unidade:");

        jLabel2.setText("Descrição:");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pitanga/img/new_20x20.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btNovo);

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pitanga/img/cancel_20x20.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btCancelar);

        btGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pitanga/img/save_20x20.png"))); // NOI18N
        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });
        jToolBar1.add(btGravar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfCodigo)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfDescricao))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbUnidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbUnidade.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbUnidade);

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jLabel5.setText("Pesquisa:");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPesquisa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir)
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        gravarUnidade();
    }//GEN-LAST:event_btGravarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        initialize();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        novaUnidade();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluirUnidade();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void initialize() {
        preencherTabela();
        this.tfPesquisa.setEnabled(true);
        this.tbUnidade.setEnabled(true);
        // Habilita a seleção na tabela
        this.tbUnidade.setRowSelectionAllowed(true);
        this.btNovo.setEnabled(true);
        this.btCancelar.setEnabled(false);
        this.btGravar.setEnabled(false);
        this.btExcluir.setEnabled(true);
        this.btSair.setEnabled(true);
        this.tfCodigo.setEnabled(false);
        this.tfDescricao.setEnabled(false);
        this.tfCodigo.setText("");
        this.tfDescricao.setText("");
        this.tfPesquisa.setText("");
        this.setTitle("Pitanga System - Unidades");
        GUIUtils.considerarEnterComoTab(this);
    }

    private void preencherTabela() {
        UnidadeDAO ud = DAOFactory.getDefaultDAOFactory().getUnidadeDAO();
        unidades = ud.listarTodos();
        if (unidades != null) {
            tbUnidade.setModel(new UnidadeTableModel(unidades));
            tbUnidade.setDefaultRenderer(Object.class, new UnidadeCellRenderer());
        }
    }

    private void novaUnidade() {
        this.btExcluir.setEnabled(false);
        this.btNovo.setEnabled(false);
        this.btCancelar.setEnabled(true);
        this.btGravar.setEnabled(true);
        this.btSair.setEnabled(false);

        this.tbUnidade.setEnabled(false);
        this.tbUnidade.setRowSelectionAllowed(false);

        this.tfPesquisa.setEnabled(false);
        this.tfCodigo.setEnabled(true);
        this.tfDescricao.setEnabled(true);
        this.tfCodigo.setDocument(new LimiteDigitos(3));
        this.tfDescricao.setDocument(new LimiteDigitos(50));
        this.tfCodigo.requestFocus();
    }

    private void gravarUnidade() {
        if ((tfCodigo.getText().trim()).equals("")) {
            JOptionPane.showMessageDialog(
                    null, "Favor informar o código da unidade!",
                    "Campo obrigatório", JOptionPane.INFORMATION_MESSAGE);
            tfCodigo.requestFocus();
        } else if (tfDescricao.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    null, "Favor informar a descrição da unidade!",
                    "Campo obrigatório", JOptionPane.INFORMATION_MESSAGE);
            tfDescricao.requestFocus();
        } else {
            Unidade unidade = new Unidade();
            unidade.setIdUnidade(tfCodigo.getText().trim());
            unidade.setDescricao(tfDescricao.getText().trim());
            UnidadeDAO uniDao = DAOFactory.getDefaultDAOFactory().getUnidadeDAO();
            uniDao.inserir(unidade);
            initialize();
        }
    }

    private void excluirUnidade() {

        int selecionada = tbUnidade.getSelectedRow();

        if (selecionada == -1) {
            JOptionPane.showMessageDialog(rootPane,
                    "- NENHUM PRODUTO SELECIONADO -",
                    "Pitanga System - EXCLUIR",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {

            UnidadeTableModel utm = new UnidadeTableModel(unidades);
            Unidade u = utm.get(selecionada);

            String codigo = u.getIdUnidade();
            String nome = u.getDescricao();

            int i = JOptionPane.showConfirmDialog(null,
                    "DESEJA MESMO EXCLIUR A UNIDADE ABAIXO?\n\n"
                    + "Código: " + codigo
                    + "\nDescrição: " + nome + "\n\n",
                    "Pitanga System - Confirmação de exclusão",
                    JOptionPane.YES_NO_OPTION);
            if (i == JOptionPane.YES_OPTION) {
                UnidadeDAO unidadeDAO = DAOFactory.getDefaultDAOFactory().getUnidadeDAO();
                if (unidadeDAO.remover(codigo)) {
                    JOptionPane.showMessageDialog(rootPane, "Unidade removida!");
                }
            }
        }
        initialize();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbUnidade;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
}
